# Generated by Django 5.2.5 on 2025-09-04 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('gpu', 'GPU'), ('cpu', 'CPU')], max_length=10)),
                ('brand', models.CharField(blank=True, max_length=80)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('condition', models.CharField(blank=True, max_length=50)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('ray_tracing', models.BooleanField(default=False)),
                ('accessories', models.JSONField(blank=True, default=list)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('pre_valuacion', models.PositiveIntegerField()),
                ('rango_min', models.PositiveIntegerField()),
                ('rango_max', models.PositiveIntegerField()),
                ('vigencia_horas', models.PositiveIntegerField(default=48)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=64)),
                ('product_name', models.CharField(blank=True, max_length=160)),
                ('product_price', models.PositiveIntegerField(default=0)),
                ('credit_applied', models.PositiveIntegerField(default=0)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('checkout_url', models.URLField()),
                ('status', models.CharField(choices=[('created', 'Created'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='created', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='canje.creditrequest')),
            ],
        ),
    ]
