# Generated by Django 5.2.5 on 2025-09-06 15:04

import canje.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canje', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditrequest',
            name='expires_at',
            field=models.DateTimeField(default=canje.models.default_expires_at),
        ),
    ]
