# Generated by Django 5.2.5 on 2025-09-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canje', '0002_alter_creditrequest_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('brand', models.CharField(blank=True, max_length=80)),
                ('series', models.CharField(blank=True, max_length=80)),
                ('category', models.CharField(choices=[('gpu-nueva', 'GPU Nueva'), ('gpu-usada', 'GPU Usada'), ('pc-reacondicionada', 'PC Reacondicionada')], max_length=40)),
                ('price', models.PositiveIntegerField()),
                ('condition', models.CharField(blank=True, max_length=50)),
                ('specs', models.JSONField(blank=True, default=list)),
                ('image', models.URLField(blank=True)),
            ],
        ),
    ]
