# Generated by Django 5.2.5 on 2025-09-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('gpu-nueva', 'GPU Nueva'), ('gpu-usada', 'GPU Usada'), ('pc-reacondicionada', 'PC Reacondicionada')], db_index=True, max_length=24)),
                ('brand', models.CharField(db_index=True, max_length=64)),
                ('series', models.CharField(blank=True, db_index=True, max_length=64)),
                ('price', models.PositiveIntegerField()),
                ('condition', models.CharField(blank=True, max_length=32)),
                ('specs', models.JSONField(blank=True, default=list)),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
